### ISSUE TITLE
热烈祝贺“我会喊666”小组Beta阶段第二次Scrum会议圆满结束

### ISSUE THREAD

**Issue by Nisces** [SE666/A404#14]
2019年12月7日晚8:00，“我会喊666”小组Beta阶段第二次Scrum会议在中国海洋大学信息科学与工程学院南楼3层召开。会议讨论并通过了《关于“信北A404会议室预约系统”前后端数据交互格式的有关报告》，确定了下阶段小组要完成的主要任务是：前端结合后端，共同完成项目。（我编不下去了）

**Comment by wangsenouc** [comment]
热烈庆祝
