### ISSUE TITLE
后端返回数据的格式

### ISSUE THREAD

**Issue by wangsenouc** [SE666/A404#15]
在用户查询申请的页面中，后端返回的使用时间能不能是“2019年10月16日 16:00-18:00”这种格式，而不是“2019-10-16 16:00:00”.
![Image of Yaktocat](https://img-blog.csdnimg.cn/20191208100355606.png)

**Comment by Nisces** [comment]
前端收到数据后可以再加工一下

**Comment by wangsenouc** [comment]
是在渲染时加工还是在JS里加工

**Comment by wangsenouc** [comment]
@Nisces

**Comment by Nisces** [comment]
在前端当作单纯的字符串处理一下
